

export const ROOT_INTO_APPLICATION  = 'ROOT_INTO_APPLICATION'

export const ROOT_INITIAL_BEGIN   = 'ROOT_INITIAL_BEGIN'
export const ROOT_INITIAL_FAILURE = 'ROOT_INITIAL_FAILURE'
export const ROOT_INITIAL_SUCCESS = 'ROOT_INITIAL_SUCCESS'